version: "3"

services:
  demoapp:
    build:
      context: ./app/
    command: python -u app.py
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/app/
    links:
      - db
  db:
    image: mongo:latest
    hostname: testmongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=coinsdb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypasswd
    volumes:
      - data:/data/db 
    ports: 
      - 27017:27017
volumes:
  data:
